### ISSUE TITLE
Host on github pages?

### ISSUE THREAD

**Issue by robiot** [j00ru/windows-syscalls#5]
It would make it easier to view the html files, without downloading them.

**Comment by mikilian** [comment]
https://j00ru.vexillium.org/syscalls/nt/64/
https://j00ru.vexillium.org/syscalls/nt/32/
https://j00ru.vexillium.org/syscalls/win32k/64/
https://j00ru.vexillium.org/syscalls/win32k/32/

**Comment by robiot** [comment]
I didn't see that in the readme before, guess im blind :laughing:.
