### ISSUE TITLE
Dead links to the syscall HTML tables in README

### ISSUE THREAD

**Issue by angusholder** [j00ru/windows-syscalls#6]
It seems that the links with **http**://j00ru.vexillium.org redirect to ynvael.coldwind.pl, then get a 404. However if you use **https**, it works correctly

Broken, redirects to ynvael.coldwind.pl domain and gets 404
http://j00ru.vexillium.org/syscalls/win32k/64/

Works if you change link to https:
https://j00ru.vexillium.org/syscalls/win32k/64/

**Comment by j00ru** [comment]
Fixed, thanks!
